version: "3.3"

services:
  alma-inventory:
    image: terrywbrady/alma-inventory-node
    ports:
      - 80:80
    volumes:
      - "./local.prop:/var/data/local.prop"
      - "./gsheet.prop.json:/usr/src/app/gsheet.prop.json"
    tty: true
    stdin_open: true
